server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/OnlineExamination?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: password
  jpa: 
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  resources:
    chain.strategy.content.enabled: true
    chain.strategy.content.paths: /**
    static-locations: classpath:/static/,classpath:/templates/