server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/OnlineExam?useSSL=false
    username: root
    password: password
  jpa: 
    show-sql: true

