server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/OnlineExam2?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
  web.resources:
    chain.strategy.content.enabled: true
    chain.strategy.content.paths: /**
    static-locations: classpath:/static/,classpath:/templates/,classpath:/templates/doExamApp/
  flyway:
    baseline-on-migrate: true
    create-schemas: true
  mail:
    Host: smtp.gmail.com
    port: 587
    username: nguyentam.angel
    password: Tam0903014696
    properties:
      mail.smtp.auth: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
      mail.smtp.starttls.enable: true
